### ISSUE TITLE
am configuration not found

### ISSUE THREAD

**Issue by ThetaRgo** [KevinWang676/Bark-Voice-Cloning#38]
2023-09-04 15:36:16,560 - modelscope - INFO - mvn_path=/home/gpuserver/python/Personal-TTS-v2/pretrain_work_dir/orig_model/mvn.npy
Traceback (most recent call last):
  File "/home/gpuserver/.conda/envs/sbhfgan/lib/python3.9/site-packages/gradio/routes.py", line 523, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/gpuserver/.conda/envs/sbhfgan/lib/python3.9/site-packages/gradio/blocks.py", line 1437, in process_api
    result = await self.call_function(
  File "/home/gpuserver/.conda/envs/sbhfgan/lib/python3.9/site-packages/gradio/blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/gpuserver/.conda/envs/sbhfgan/lib/python3.9/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/gpuserver/.conda/envs/sbhfgan/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/gpuserver/.conda/envs/sbhfgan/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/gpuserver/.conda/envs/sbhfgan/lib/python3.9/site-packages/gradio/utils.py", line 865, in wrapper
    response = f(*args, **kwargs)
  File "/home/gpuserver/python/Personal-TTS-v2/main.py", line 145, in infer
    model_id = SambertHifigan(os.path.join(model_dir, "orig_model"), **kwargs)
  File "/home/gpuserver/.conda/envs/sbhfgan/lib/python3.9/site-packages/modelscope/models/audio/tts/sambert_hifi.py", line 53, in __init__
    self.voices, self.voice_cfg, self.lang_type = self.load_voice(
  File "/home/gpuserver/.conda/envs/sbhfgan/lib/python3.9/site-packages/modelscope/models/audio/tts/sambert_hifi.py", line 107, in load_voice
    return self.build_voice_from_custom(model_dir, custom_ckpt)
  File "/home/gpuserver/.conda/envs/sbhfgan/lib/python3.9/site-packages/modelscope/models/audio/tts/sambert_hifi.py", line 90, in build_voice_from_custom
    voice = Voice(
  File "/home/gpuserver/.conda/envs/sbhfgan/lib/python3.9/site-packages/modelscope/models/audio/tts/voice.py", line 158, in __init__
    raise TtsModelConfigurationException(
modelscope.utils.audio.tts_exceptions.TtsModelConfigurationException: modelscope error: am configuration not found

**Comment by KevinWang676** [comment]
这个是因为模型训练阶段出错了，推理语音时没有对应的模型文件

**Comment by rucieryi369** [comment]
你的问题解决了吗

**Comment by lingfengchencn** [comment]
同问，请问怎么处理？
如果说模型训练出错的话，可是提示训练成功了。查看log也没有error。

**Comment by NaMoCv** [comment]
严重怀疑这个up被各个那几家大厂充值了，逼着大家有显卡不用去用那哪些在线程序，但是慢得要死。
