### ISSUE TITLE
有没有windows本地部署成功的并能成功跑起来的，请指教下，谢谢了。

### ISSUE THREAD

**Issue by oktetopython** [KevinWang676/Bark-Voice-Cloning#66]
win10部署了2次了就是跑不起来，完全是按照说明来操作的。

`smallmodels=False
enablemps=False
offloadcpu=False
forcecpu=False
autolaunch=True

Preloading Models

Loading text model from ./models\text_2.pt to cuda
Loading coarse model from ./models\coarse_2.pt to cuda
Loading fine model from ./models\fine_2.pt to cuda
Launching Bark Voice Cloning UI Server
Running on local URL:  http://127.0.0.1:7860
Running on public URL: https://d57f7780b073c9699f.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)
2023-11-13 17:19:02 | ERROR | asyncio | Task exception was never retrieved
future: <Task finished name='skwmew7qhyf_6' coro=<Queue.process_events() done, defined at H:\Bark-Voice-Cloning\venv\lib\site-packages\gradio\queueing.py:343> exception=1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': [{'data': 'data:...on_hash': 'skwmew7qhyf'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.4/v/missing>
Traceback (most recent call last):
  File "H:\Bark-Voice-Cloning\venv\lib\site-packages\gradio\queueing.py", line 347, in process_events
    client_awake = await self.gather_event_data(event)
  File "H:\Bark-Voice-Cloning\venv\lib\site-packages\gradio\queueing.py", line 220, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
  File "H:\Bark-Voice-Cloning\venv\lib\site-packages\gradio\queueing.py", line 456, in get_message
    return PredictBody(**data), True
  File "H:\Bark-Voice-Cloning\venv\lib\site-packages\pydantic\main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': [{'data': 'data:...on_hash': 'skwmew7qhyf'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.4/v/missing
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.`

**Comment by ycpan** [comment]
linux 也遇到了上述问题

**Comment by xiao-rao** [comment]
代码出错了

**Comment by 1044690543** [comment]
俺也一样有这个报错
