### ISSUE TITLE
colab 训练提示 “libcuda.so cannot found”

### ISSUE THREAD

**Issue by sg0771** [KevinWang676/Bark-Voice-Cloning#79]
colab 训练提示 “libcuda.so cannot found”

**Comment by sg0771** [comment]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 497, in process_events
    response = await self.call_prediction(awake_events, batch)
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 468, in call_prediction
    raise Exception(str(error) if show_error else None) from error
Exception: libcuda.so cannot found!

**Comment by vensend** [comment]
> colab 训练提示 “libcuda.so cannot found”

老哥找到解决方案吗

**Comment by sg0771** [comment]
没有

**Comment by KevinWang676** [comment]
看一下这个解决方法，应该有效：[link](https://github.com/pytorch/pytorch/issues/107960#issuecomment-1783432552)
