### ISSUE TITLE
colab运行离线批量ASR报错

### ISSUE THREAD

**Issue by qlql489** [KevinWang676/Bark-Voice-Cloning#87]
报错信息如下
 pip install -U rotary_embedding_torch
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/modelscope/utils/registry.py", line 212, in build_from_cfg
    return obj_cls(**args)
  File "/usr/local/lib/python3.10/dist-packages/modelscope/pipelines/audio/asr_inference_pipeline.py", line 123, in __init__
    from funasr.bin import asr_inference_launch
ImportError: cannot import name 'asr_inference_launch' from 'funasr.bin' (/usr/local/lib/python3.10/dist-packages/funasr/bin/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/gpt-sovits/tools/damo_asr/cmd-asr.py", line 9, in <module>
    inference_pipeline = pipeline(
  File "/usr/local/lib/python3.10/dist-packages/modelscope/pipelines/builder.py", line 170, in pipeline
    return build_pipeline(cfg, task_name=task)
  File "/usr/local/lib/python3.10/dist-packages/modelscope/pipelines/builder.py", line 65, in build_pipeline
    return build_from_cfg(
  File "/usr/local/lib/python3.10/dist-packages/modelscope/utils/registry.py", line 215, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
ImportError: AutomaticSpeechRecognitionPipeline: cannot import name 'asr_inference_launch' from 'funasr.bin' (/usr/local/lib/python3.10/dist-packages/funasr/bin/__init__.py)

**Comment by LauraGPT** [comment]
The code should update with funasr-1.0,
Solution in here: https://github.com/alibaba-damo-academy/FunASR/discussions/1319
