### ISSUE TITLE
colab运行离线ASR报错

### ISSUE THREAD

**Issue by rongchenlin** [KevinWang676/Bark-Voice-Cloning#88]
2024-01-24 12:16:50,707 - modelscope - WARNING - ('PIPELINES', 'auto-speech-recognition', 'asr-inference') not found in ast index file
Traceback (most recent call last):
  File "/lders/gpt-sovits/tools/damo_asr/cmd-asr.py", line 9, in <module>
    inference_pipeline = pipeline(
  File "/usr/local/lib/python3.10/dist-packages/modelscope/pipelines/builder.py", line 170, in pipeline
    return build_pipeline(cfg, task_name=task)
  File "/usr/local/lib/python3.10/dist-packages/modelscope/pipelines/builder.py", line 65, in build_pipeline
    return build_from_cfg(
  File "/usr/local/lib/python3.10/dist-packages/modelscope/utils/registry.py", line 198, in build_from_cfg
    raise KeyError(
KeyError: 'asr-inference is not in the pipelines registry group auto-speech-recognition. Please make sure the correct version of ModelScope library is used.'

**Comment by LauraGPT** [comment]
The code should update with funasr-1.0,
Solution in here: https://github.com/alibaba-damo-academy/FunASR/discussions/1319

**Comment by rongchenlin** [comment]
Thanks, your solution is very effective.

**Comment by KevinWang676** [comment]
@rongchenlin The original code in Colab Notebook would still work although it is not recommended by ModelScope.
